fullnameOverride: blog-db

auth:
  rootPassword: rootpassword
  username: bloguser
  password: blogpass
  database: blog_db
  authenticationPlugin: mysql_native_password

primary:
  service:
    type: NodePort
    nodePorts:
      mysql: 31060
  port: 3306

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 768Mi
      cpu: 750m

initdbScriptsConfigMap: mysql-initdb
