apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pod
  namespace: production
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: upload-volume
      mountPath: /upload
  volumes:
  - name: upload-volume
    persistentVolumeClaim:
      claimName: upload-pvc
