apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
