---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-tomcat
  labels:
    app: blog-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-tomcat
  template:
    metadata:
      labels:
        app: blog-tomcat
    spec:
      containers:
      - name: tomcat
        image: 192.168.0.101:5000/blog-tomcat:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blog-tomcat
spec:
  type: NodePort
  selector:
    app: blog-tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
